runtime: python37

env_variables:
  includes:
  - ../app_env.yaml

handlers:
  # Serve static files
- url: /static
  static_dir: static

- url: /api/.*
  script: auto

- url: /twilio/.*
  script: auto

  # Everything not caught above goes to main app.
- url: /css
  static_dir: static/frontend/css

- url: /js
  static_dir: static/frontend/js

- url: /img
  static_dir: static/frontend/img

- url: /.*
  static_files: static/frontend/index.html
  upload: static/frontend/index.html