"""add active flag to Shelter table to allow shutting of a shelter without delteing it

Revision ID: 03c60f6ff751
Revises: ac06442bf4e6
Create Date: 2018-11-02 17:56:36.514245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c60f6ff751'
down_revision = 'ac06442bf4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelters', sa.Column('active', sa.Boolean(), server_default='TRUE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelters', 'active')
    # ### end Alembic commands ###
