"""empty message

Revision ID: 60fc54da6b93
Revises: 9d020e21a8ba
Create Date: 2018-10-29 18:53:45.514571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60fc54da6b93'
down_revision = '9d020e21a8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('timecall', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('calls', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('calls', 'timecall')
    # ### end Alembic commands ###
