"""fix case

Revision ID: 6bb9220f884d
Revises: 72668c4a1bc7
Create Date: 2018-10-17 14:36:27.299076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb9220f884d'
down_revision = '72668c4a1bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelters', sa.Column('login_id', sa.String(length=16), nullable=True))
    op.drop_constraint('shelters_loginID_key', 'shelters', type_='unique')
    op.create_unique_constraint(None, 'shelters', ['login_id'])
    op.drop_column('shelters', 'loginID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelters', sa.Column('loginID', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shelters', type_='unique')
    op.create_unique_constraint('shelters_loginID_key', 'shelters', ['loginID'])
    op.drop_column('shelters', 'login_id')
    # ### end Alembic commands ###
