"""Unique Phone for Shelters

Revision ID: 6f557601a161
Revises: 6bb9220f884d
Create Date: 2018-10-19 22:14:47.185658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f557601a161'
down_revision = '6bb9220f884d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shelters', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shelters', type_='unique')
    # ### end Alembic commands ###
