"""initial migration

Revision ID: 72668c4a1bc7
Revises: 
Create Date: 2018-10-17 13:27:50.524484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72668c4a1bc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('loginID', sa.String(length=16), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loginID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('bedcount', sa.Integer(), nullable=True),
    sa.Column('from_number', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calls')
    op.drop_table('shelters')
    # ### end Alembic commands ###
