"""add logs table to replace calls for more general logging

Revision ID: 7da1f78c3f73
Revises: 6280ce08b3a1
Create Date: 2018-11-16 16:28:01.732834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da1f78c3f73'
down_revision = '6280ce08b3a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shelter_id', sa.Integer(), nullable=True),
    sa.Column('from_number', sa.String(length=16), nullable=True),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('parsed_text', sa.String(), nullable=True),
    sa.Column('contact_type', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
