"""add 'visible' flag to shelters

Revision ID: 7f541e8c6290
Revises: 58e943eb1882
Create Date: 2019-05-06 10:53:51.186554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f541e8c6290'
down_revision = '58e943eb1882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelters', sa.Column('visible', sa.Boolean(), server_default='TRUE', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelters', 'visible')
    # ### end Alembic commands ###
