"""fix typo in  prefs table

Revision ID: 84f41dba40eb
Revises: b4dc40e2f510
Create Date: 2018-12-27 11:54:38.867930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f41dba40eb'
down_revision = 'b4dc40e2f510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prefs', sa.Column('enforce_hours', sa.Boolean(), nullable=True))
    op.drop_column('prefs', 'enfore_hours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prefs', sa.Column('enfore_hours', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('prefs', 'enforce_hours')
    # ### end Alembic commands ###
