"""make shelter id non-nullable

Revision ID: 9d020e21a8ba
Revises: fdbf3b8681ff
Create Date: 2018-10-26 16:22:59.316589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d020e21a8ba'
down_revision = 'fdbf3b8681ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'shelter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'shelter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
