"""add action to logs

Revision ID: 9e42472e63d1
Revises: 7da1f78c3f73
Create Date: 2018-11-16 17:29:45.835256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e42472e63d1'
down_revision = '7da1f78c3f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'action')
    # ### end Alembic commands ###
