"""add public flag to Shelter

Revision ID: a5560fbe7ac9
Revises: fb01e31dd3fd
Create Date: 2020-04-06 15:23:51.173937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5560fbe7ac9'
down_revision = 'fb01e31dd3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelters', sa.Column('public', sa.Boolean(), server_default='TRUE', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelters', 'public')
    # ### end Alembic commands ###
