"""add personcount to Count table to allow number or people to be recorded

Revision ID: ac3f881db623
Revises: cd5f307e1854
Create Date: 2018-11-21 11:45:56.100264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3f881db623'
down_revision = 'cd5f307e1854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counts', sa.Column('personcount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counts', 'personcount')
    # ### end Alembic commands ###
