"""add prefs table

Revision ID: b4dc40e2f510
Revises: ac3f881db623
Create Date: 2018-12-27 10:45:12.052689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dc40e2f510'
down_revision = 'ac3f881db623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prefs',
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('enfore_hours', sa.Boolean(), nullable=True),
    sa.Column('open_time', sa.String(), nullable=True),
    sa.Column('close_time', sa.String(), nullable=True),
    sa.Column('start_day', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('app_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefs')
    # ### end Alembic commands ###
