"""Add contact type to calls

Revision ID: c9147995db59
Revises: 247f66e73d2a
Create Date: 2018-11-03 13:59:07.767087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'c9147995db59'
down_revision = '247f66e73d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM("unknown", "incoming_text", "incoming_call", "outgoing_call", name='contact_types')
    enum.create(op.get_bind(), checkfirst=False)
    op.add_column('calls', sa.Column('contact_type', sa.Enum(name='contact_types'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'contact_type')
    ENUM(name="contact_types").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
