"""add description to shelters

Revision ID: fb01e31dd3fd
Revises: 7f541e8c6290
Create Date: 2019-10-27 12:48:55.095106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb01e31dd3fd'
down_revision = '7f541e8c6290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shelters', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shelters', 'description')
    # ### end Alembic commands ###
